### ISSUE TITLE
Cannot run on MacOS 10.13.6

### ISSUE THREAD

**Issue by talyguryn** [canonical-web-and-design/multipass.run#75] opened 2020-02-15 12:49 UTC
on the site: 

![image](https://user-images.githubusercontent.com/15259299/74588080-ae286780-500a-11ea-89f7-f065f7d67e99.png)

but on my mac:

![image](https://user-images.githubusercontent.com/15259299/74588063-9355f300-500a-11ea-8550-90d0f2752114.png)

**Comment by matthewpaulthomas** [comment] 2020-02-18 13:02
@talyguryn Thanks for this report. I see from [multipass#1258](https://github.com/canonical/multipass/issues/1258) and [multipass#1330](https://github.com/canonical/multipass/issues/1330) that the Multipass engineers haven’t worked out what the minimum version is, or what it should be. I’ll encourage them to reach a conclusion.

**Comment by Saviq** [comment] 2020-02-19 16:27
Duplicate of multipass#1258

**Comment by Saviq** [comment] 2020-02-19 16:28
@matthewpaulthomas you can probably close this here.

**Comment by matthewpaulthomas** [comment] 2020-02-20 16:16
@Saviq I think the Multipass code and the Web site will likely be fixed by different people at different times in different PRs. If you get Multipass working on 10.10.3 again, then great, nothing to do here. The discussion in #1258 does not suggest this is likely at the moment.

**Comment by matthewpaulthomas** [comment] 2020-03-05 09:25
From [canonical/multipass#1258](https://github.com/canonical/multipass/issues/1258#issuecomment-592484146):
> Hi all, we've looked around a lot and decided to settle on macOS 10.12 Sierra as our lowest supported macOS version.

So, I’ll update the site to match.

**Closed** 2020-03-05 09:55 UTC
Labels: Priority: High
